name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Ensure SSH directory exists
      run: mkdir -p ~/.ssh

    - name: Generate SSH key if not exists
      run: |
        if [ ! -f ~/.ssh/id_rsa ]; then
          ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa
        fi

    - name: Create bin directory and link littlesecrets CLI
      run: |
        mkdir -p bin
        ln -srf src/sh/littlesecrets.sh bin/littlesecrets
        chmod +x bin/littlesecrets

    - name: Add repo bin to PATH
      run: echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

    - name: Run tests
      run: make test